### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by hulkwork** [FlorianVal/Gradio_chat_demo#1]
Is that possible to add cache folder on the docker compose, because all the time download the model : 

```
version: "3.8"

services:
  gradio_chatbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: "http://model:8000/v1"
        MODEL: "${MODEL}"
    ports:
      - "7860:7860"
    links:
      - model

  model:
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    environment:
      HF_TOKEN: "${HF_TOKEN}"
      MODEL: "${MODEL}"
    command: ["--host", "0.0.0.0", "--model", "${MODEL}", "--dtype", "half"] # Change to Bfloat16 if newer GPU
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      - "~/.cache/huggingface/:/root/.cache/huggingface/"

```

on the service model or add a specific volume
